"""empty message

Revision ID: 1e8e711af1b5
Revises: 30bc2f98f7b0
Create Date: 2022-03-08 13:39:00.795991

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1e8e711af1b5'
down_revision = '30bc2f98f7b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'add_column')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('add_column', mysql.TEXT(), nullable=True, comment='更新的'))
    # ### end Alembic commands ###
