"""empty message

Revision ID: 30bc2f98f7b0
Revises: 2c26f3fc2f1f
Create Date: 2022-03-08 13:38:26.104738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30bc2f98f7b0'
down_revision = '2c26f3fc2f1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('add_column', sa.Text(), nullable=True, comment='更新的'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'add_column')
    # ### end Alembic commands ###
