"""empty message

Revision ID: 9c4b480d15db
Revises: 1e8e711af1b5
Create Date: 2022-03-08 15:27:49.807781

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9c4b480d15db'
down_revision = '1e8e711af1b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('achievement')
    op.add_column('course', sa.Column('course_name', sa.String(length=64), nullable=True, comment='课程名称'))
    op.add_column('course', sa.Column('grade', sa.Integer(), nullable=True, comment='成绩'))
    op.alter_column('course', 'name',
               existing_type=mysql.VARCHAR(length=64),
               comment='学生名称',
               existing_comment='课程名称',
               existing_nullable=True)
    op.create_unique_constraint(None, 'course', ['course_name'])
    op.create_foreign_key(None, 'course', 'student', ['name'], ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'course', type_='foreignkey')
    op.drop_constraint(None, 'course', type_='unique')
    op.alter_column('course', 'name',
               existing_type=mysql.VARCHAR(length=64),
               comment='课程名称',
               existing_comment='学生名称',
               existing_nullable=True)
    op.drop_column('course', 'grade')
    op.drop_column('course', 'course_name')
    op.create_table('achievement',
    sa.Column('score', mysql.DECIMAL(precision=10, scale=0), nullable=True, comment='分数'),
    sa.Column('student_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('course_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name='achievement_ibfk_1'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name='achievement_ibfk_2'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
